URL = 'https://youtu.be/vVL6NFzr0Rg?si=uS-n4RibJY1hIyaj'
TEMP_AUDIO_DIRECTORY_PATH = '/home/nicolas/Projets DS/TranscriptToAnki/temp_audio'
TRANSCRIPTIONS_DIRECTORY_PATH = '/home/nicolas/Projets DS/TranscriptToAnki/transcriptions'
COOKIES_PATH = '/home/nicolas/Projets DS/TranscriptToAnki/cookies.txt'
DENO_PATH = '/usr/bin/deno'